name: CI / Gradle

on: [pull_request]

defaults:
  run:
    working-directory: norsedictionaries

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        run: ./gradlew build
      - name: Run tests
        run: ./gradlew test